[package]
name = "xcb-hide-shadow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = { version = "1.1.1", features = ["debug_atom_names", "sync", "xinput", "composite"] }